### ISSUE TITLE
program datayı

### ISSUE THREAD

**Issue by ysf72byk** [ozdemiremrah/unlimited-ipv6-proxy#1]
1-program mantığı nedir ,ne işeyarar ?
2-detaylı kullanım videosu veya açıklaması ekler misiniz ?

yanıtınız için teşekkürler.

**Comment by ozdemiremrah** [comment]
1- Program ipv6 tanımlı sunucularda, interface'e istek sırasında talep edilen ipv6 adresini tanımlar ve isteğin bu ip adresinden çıkması için proxy görevi görür. 
2- Anlatım videosu ekleyemem. Basitçe anlamak için; program config dosyasını doğru şekilde ayarlayıp ayağa kaldırdığınızda, http request sırasında header'a vereceğiniz **x-proxy-ip** parametresini (tabi ki size tanımlı ipv6 bloğu içinde olan) alır ve ip adresini interface'e tanımlar. İsteğinde bu ip adresinden dışarı çıkması için zorlar.
